import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TeacherOnboardProvider } from "@/context/TeacherOnboardContext";
import { SchoolOnboardProvider } from "@/context/SchoolOnboardContext";
import { AddSubjectsProvider } from "@/context/AddSubjectsContext";
import { AddStudentsProvider } from "@/context/AddStudentsContext";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TeacherOnboardProvider>
          <SchoolOnboardProvider>
            <AddSubjectsProvider>
              <AddStudentsProvider>
                {children}
                <Toaster position="bottom-right" />
              </AddStudentsProvider>
            </AddSubjectsProvider>
          </SchoolOnboardProvider>
        </TeacherOnboardProvider>
      </body>
    </html>
  );
}
