"use client";

import { useState, useEffect } from "react";
import { usePathname, useRouter } from "next/navigation";

import { LoadingButton } from "@/shared-components/loading-button";
import { SecuritySetupModal } from "@/shared-components/security-setup-modal";
import { SchoolAndTermMgt } from "@/shared-components/school-and-term-mgt";
import { ErrorBanner } from "@/shared-components/error-banner";

import { Button } from "@/shadcn/ui/button";
import { Card, CardContent } from "@/shadcn/ui/card";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/shadcn/ui/form";
import { Input } from "@/shadcn/ui/input";
import { Textarea } from "@/shadcn/ui/textarea";

import { zodResolver } from "@hookform/resolvers/zod";
import { useForm, type ControllerRenderProps } from "react-hook-form";
import { z } from "zod";

import { toast } from "sonner";
import { Eye, EyeOff, Copy, Check } from "lucide-react";

import { SchoolFormCardSkeleton } from "./loading";
import { authClient } from "@/src/auth-client";
import { getErrorMessage } from "@/fetcher/mutations";
import { useUser } from "@/contexts/user-context";


// Organisation schema
// Convert empty strings to undefined and validate email if provided
const emailWithTransform = z
  .union([z.string(), z.undefined()])  // allow undefined or string values
  .transform((v) => (v && typeof v === 'string' && v.trim() !== "" ? v.trim() : undefined))  // convert non-string values or empty strings to undefined
  .refine(   // custom validation rule
    (val) => {
      // If undefined or empty, it's valid (optional field)
      if (!val) return true;   // pass undefined through
      // Otherwise, validate it's a valid email
      return z.email().safeParse(val).success;
    },
    { message: "Invalid email address" }
  )
  .nullable().optional();
const organizationSchema = z.object({
  id: z.string().nullable().optional(),   // optional to accommodate creation (id is autogenerated by the database on creation)
  name: z.string().trim().min(1, { message: "School name is required" }),
  slug: z.string().optional().default("autogenerate"),   // registration ID (defaults to "autogenerate" if not provided)
  // logo: z.string().optional(),
  metadata: z.object({
    address: z.string().nullable().optional(),
    motto: z.string().nullable().optional(),
    telephone: z.string().nullable().optional(),
    email: emailWithTransform,
  }).optional(),
});
type OrganizationFormValues = z.input<typeof organizationSchema>;  // Generate types from the schema

type ActiveOrganisation = NonNullable<
  ReturnType<typeof authClient.useActiveOrganization>["data"]
>;

// Better Auth errors expose .message and .status directly (not axios-shaped)
function getBetterAuthHttpStatus(err: unknown): number | undefined {
  const status = (err as { status?: number })?.status
    ?? (err as { response?: { status?: number } })?.response?.status;
  return typeof status === "number" ? status : undefined;
}

// Get the better auth error message from the error
function getBetterAuthErrorMessage(
  err: unknown,
  fallback = "An unexpected error occurred. Please try again.",
): string {
  const status = getBetterAuthHttpStatus(err);
  if (status === 401) return "Your session has expired. Please sign in again.";
  if (status === 403) return "You don't have permission to perform this action.";
  const message = (err as { message?: string })?.message;
  return message || getErrorMessage(err, fallback);
}

// Map the active organisation to the form values
function organisationToFormValues(org: ActiveOrganisation): OrganizationFormValues {
  return {
    name: org.name ?? "",
    slug: org.slug ?? "autogenerate",
    metadata: {
      address: org.metadata?.address ?? "",
      motto: org.metadata?.motto ?? "",
      telephone: org.metadata?.telephone ?? "",
      email: org.metadata?.email ?? "",
    },
  };
}

function buildMetadataPayload(metadata: OrganizationFormValues["metadata"]) {
  return {
    address: metadata?.address?.trim() || null,
    motto: metadata?.motto?.trim() || null,
    telephone: metadata?.telephone?.trim() || null,
    email: metadata?.email?.trim() || null,
  };
}

// School form component
export function SchoolForm() {
  // use router to handle redirects
  const router = useRouter();
  const pathname = usePathname();

  // Org admin gate — disable management features for non-orgadmin users
  const { user } = useUser();
  const canManage = user?.role === "orgadmin";

  // Get the active organisation as the school (TODO: Set active organisation on session creation as db hook)
  const {
    data: activeOrganisation,
    isPending: isActiveOrganisationPending,
    error: activeOrganisationError,
    refetch: refetchActiveOrganisation,
  } = authClient.useActiveOrganization();
  // On error, fall back to null. Otherwise, use the fetched school.
  const school = activeOrganisation ?? null;

  // likewise, set loading state
  const isUpdate = !!school;

  // organisation slug === registration id
  const [registrationId, setRegistrationId] = useState<string | null>(null);
  const [showRegistrationId, setShowRegistrationId] = useState(false);
  // flag to show/hide the copied icon
  const [copied, setCopied] = useState(false);

  // Handle authentication redirects: use the status code to determine the redirect (401, 403)
  function handleAuthRedirect(err: unknown): boolean {
    const status = getBetterAuthHttpStatus(err);
    if (status === 401) {
      toast.error("You are not authenticated. Please sign in to continue");
      router.replace(`/sign-in?redirect=${pathname}`);
      return true;
    }
    if (status === 403) {
      toast.error("You are not authorized to access this page. Please contact your admin if you believe this is an error.");
      router.replace("/forbidden");
      return true;
    }
    return false;  // if the error is not 401 or 403, return false (no redirect)
  }

  // Retry active organisation fetch
  function retryActiveOrganisationFetch() {
    void refetchActiveOrganisation?.();
  }

  useEffect(() => {
    if (!activeOrganisationError) return;
    const status = getBetterAuthHttpStatus(activeOrganisationError);
    if (status === 401) {
      router.replace(`/sign-in?redirect=${pathname}`);
    } else if (status === 403) {
      router.replace("/forbidden");
    }
  }, [activeOrganisationError, router, pathname]);

  // handle copy to clipboard
  async function handleCopy() {
    if (!registrationId) return;
    try {
      await navigator.clipboard.writeText(registrationId);
      // show the copied icon
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error("Could not copy registration ID. Please copy it manually.");
    }
  }

  // form validation with zodResolver and default values
  const form = useForm<OrganizationFormValues>({
    resolver: zodResolver(organizationSchema),
    defaultValues: {
      name: "",
      slug: "autogenerate",
      metadata: { address: "", motto: "", telephone: "", email: "" },
    },
  });

  // Sync form + registrationId once the active organisation resolves
  useEffect(() => {
    // If there is no active organisation, return
    if (!activeOrganisation) return;
    // Otherwise, reset the form with the active organisation data
    form.reset(organisationToFormValues(activeOrganisation));
    setRegistrationId(activeOrganisation.slug ?? null);
  }, [activeOrganisation, form]);

  async function onSubmit(formData: OrganizationFormValues) {
    if (!canManage) return;  // return early if the user is not an org admin

    try {
      const metadata = buildMetadataPayload(formData.metadata);

      // detect whether the submission is for update/creation
      // If we're updating
      if (isUpdate) {
        if (!school?.id) {
          toast.error("Failed to save school information", {
            description: "School id is missing. Please refresh and try again.",
          });
          return;
        }

        const { error: updateError } = await authClient.organization.update({
          data: {
            name: formData.name,
            // slug omitted — registration ID is not editable from this form
            metadata,
          },
          organizationId: school.id,
        });

        // If there is an update error, throw it
        if (updateError) throw updateError;

        // If no error, show success toast
        toast.success("School information saved successfully", {
          description: "Your school details have been saved",
        });

      } else {
        // If we're creating
        const { data: createData, error: createError } = await authClient.organization.create({
          // id: autogenerated by db on creation
          name: formData.name,
          slug: "autogenerate",
          // logo: formData.logo,
          metadata,
        });

        // If there is a create error, throw it
        if (createError) throw createError;

        if (!createData?.slug) {
          toast.warning("School may have been created but the registration ID was not returned. Please refresh.");
          return;
        }

        // if creation is successful, set the registration ID immediately so the admin can copy it
        setRegistrationId(createData.slug);

        // set the new school as the active organisation
        const { error: activeError } = await authClient.organization.setActive({
          organizationId: createData.id,
          organizationSlug: createData.slug,
        });

        // If setActive fails, the school exists but the session may not reflect it yet
        if (activeError) {
          toast.warning("School created, but it could not be set as active. Please refresh the page.", {
            description: getBetterAuthErrorMessage(activeError, "Failed to activate the new school."),
          });
          return;
        }

        // If no error, show success toast
        toast.success("School information saved successfully", {
          description: "Your school details have been saved",
        });
      }
    } catch (err: unknown) {
      if (!handleAuthRedirect(err)) {
        toast.error("Failed to save school information", {
          description: getBetterAuthErrorMessage(err, "An error occurred while saving the school information"),
        });
      }
    }
  }

  // Discard changes — revert to last saved organisation snapshot (or empty defaults on create)
  function handleDiscard() {
    if (activeOrganisation) {
      form.reset(organisationToFormValues(activeOrganisation));
      return;
    }
    form.reset();
  }

  const isComponentLoading = isActiveOrganisationPending;

  return (
    <>
      {/* Page Header */}
      <SchoolAndTermMgt title="School Management" />

      {/* Shown if 2FA is not yet enabled */}
      <SecuritySetupModal />

      {/* Error banner — shown inline so the header and security modal remain visible */}
      {activeOrganisationError && (
        <ErrorBanner
          title="Could not load school information"
          message={getBetterAuthErrorMessage(
            activeOrganisationError,
            "Failed to load saved school information. Please try again.",
          )}
          onRetry={retryActiveOrganisationFetch}
        />
      )}

      {/* School Form Card — skeleton while active org resolves; hidden on fetch error */}
      {isComponentLoading ? (
        <SchoolFormCardSkeleton />
      ) : !activeOrganisationError && (
      <Card className="border shadow-md">
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">

              {/* School Information Section */}
              <section className="space-y-4">

                {/* School Name */}
                <FormField
                  control={form.control}
                  name="name"
                  render={({ field }: { field: ControllerRenderProps<OrganizationFormValues, "name"> }) => (
                    <FormItem>
                      <FormLabel className="text-sm md:text-base text-muted-foreground font-semibold">
                        School Name<span className="text-destructive text-base">*</span>
                      </FormLabel>
                      <FormControl>
                        <Input
                          type="text"
                          {...field}
                          readOnly={!canManage}
                          placeholder="Enter school name"
                          className="h-10 md:h-12 text-sm md:text-base transition-colors hover:border-input focus:border-primary"
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* School Address */}
                <FormField
                  control={form.control}
                  name="metadata.address"
                  render={({ field }: { field: ControllerRenderProps<OrganizationFormValues, "metadata.address"> }) => (
                    <FormItem>
                      <FormLabel className="text-sm md:text-base text-muted-foreground font-semibold">Address</FormLabel>
                      <FormControl>
                        <Input
                          type="text"
                          {...field}
                          value={field.value ?? ""}
                          readOnly={!canManage}
                          placeholder="Enter school address or location"
                          className="h-10 md:h-12 text-sm md:text-base transition-colors hover:border-input focus:border-primary"
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* School Motto */}
                <FormField
                  control={form.control}
                  name="metadata.motto"
                  render={({ field }: { field: ControllerRenderProps<OrganizationFormValues, "metadata.motto"> }) => (
                    <FormItem>
                      <FormLabel className="text-sm md:text-base text-muted-foreground font-semibold">Motto</FormLabel>
                      <FormControl>
                        <Textarea
                          {...field}
                          value={field.value ?? ""}
                          readOnly={!canManage}
                          placeholder="Enter your school motto if you want this to appear on the result sheet"
                          className="min-h-20 text-sm md:text-base transition-colors hover:border-input focus:border-primary"
                          rows={3}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* School Telephone and Email */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <FormField
                    control={form.control}
                    name="metadata.telephone"
                    render={({ field }: { field: ControllerRenderProps<OrganizationFormValues, "metadata.telephone"> }) => (
                      <FormItem>
                        <FormLabel className="text-sm md:text-base text-muted-foreground font-semibold">Telephone</FormLabel>
                        <FormControl>
                          <Input
                            {...field}
                            value={field.value ?? ""}
                            readOnly={!canManage}
                            type="tel"
                            placeholder="Enter school telephone number"
                            className="h-10 md:h-12 text-sm md:text-base transition-colors hover:border-input focus:border-primary"
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  {/* School Email */}
                  <FormField
                    control={form.control}
                    name="metadata.email"
                    render={({ field }: { field: ControllerRenderProps<OrganizationFormValues, "metadata.email"> }) => (
                      <FormItem>
                        <FormLabel className="text-sm md:text-base text-muted-foreground font-semibold">Email</FormLabel>
                        <FormControl>
                          <Input
                            {...field}
                            value={field.value ?? ""}
                            readOnly={!canManage}
                            type="email"
                            placeholder="Enter school email address"
                            className="h-10 md:h-12 text-sm md:text-base transition-colors hover:border-input focus:border-primary"
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>
              </section>

              {/* School Registration ID — shown once a school exists */}
              {registrationId && (
                <section className="space-y-2 pt-4 border-t border-border">
                  <div>
                    <p className="text-sm md:text-base text-muted-foreground font-semibold">
                      School Registration ID
                    </p>
                    <p className="text-xs text-muted-foreground mt-0.5">
                      Share this ID with teachers so they can register and join your school.
                    </p>
                  </div>
                  <div className="relative">
                    {/* Readonly value */}
                    <Input
                      readOnly
                      disabled
                      type="text"
                      value={showRegistrationId ? registrationId : "*****************"}
                      className="h-12 md:h-14 text-sm md:text-base pr-20 font-mono disabled:opacity-100 disabled:cursor-default [&::-ms-reveal]:hidden"
                    />
                    {/* Eye toggle */}
                    <Button
                      type="button"
                      variant="ghost"
                      size="icon"
                      onClick={() => setShowRegistrationId((v) => !v)}
                      title={showRegistrationId ? "Hide registration ID" : "Show registration ID"}
                      aria-label={showRegistrationId ? "Hide registration ID" : "Show registration ID"}
                      className="absolute right-10 top-1/2 -translate-y-1/2 h-8 w-8 text-muted-foreground hover:text-foreground"
                    >
                      {showRegistrationId ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                    </Button>
                    {/* Copy to clipboard */}
                    <Button
                      type="button"
                      variant="ghost"
                      size="icon"
                      onClick={handleCopy}
                      title="Copy registration ID"
                      aria-label="Copy registration ID"
                      className="absolute right-1 top-1/2 -translate-y-1/2 h-8 w-8 text-muted-foreground hover:text-foreground"
                    >
                      {copied ? <Check className="h-4 w-4 text-green-500" /> : <Copy className="h-4 w-4" />}
                    </Button>
                  </div>
                </section>
              )}

              {/* Submit / Discard Buttons */}
              {canManage && (
                <div className="pt-4 border-t border-border mt-4">
                  <div className="flex justify-center gap-3">
                    {/* Discard Changes Button */}
                    <Button
                      type="button"
                      variant="outline"
                      disabled={!form.formState.isDirty || form.formState.isSubmitting}
                      onClick={handleDiscard}
                      className="w-max h-10 md:h-12 text-sm md:text-base font-medium shadow-sm hover:shadow transition-shadow cursor-pointer"
                    >
                      Discard Changes
                    </Button>
                    {/* Save Changes Button */}
                    <LoadingButton
                      type="submit"
                      loading={form.formState.isSubmitting}
                      disabled={!form.formState.isDirty}
                      className="w-max h-10 md:h-12 text-sm md:text-base font-medium shadow-sm hover:shadow transition-shadow cursor-pointer"
                    >
                      Save Changes
                    </LoadingButton>
                  </div>
                </div>
              )}

            </form>
          </Form>
        </CardContent>
      </Card>
      )}
    </>
  );
}
