"use client";

import { useState, useEffect } from "react";
import { usePathname, useRouter } from "next/navigation";
import { LoadingButton } from "@/shared-components/loading-button";
import { SecuritySetupModal } from "@/shared-components/security-setup-modal";
import { SchoolAndTermMgt } from "@/shared-components/school-and-term-mgt";
import { ErrorBanner } from "@/shared-components/error-banner";
import { Button } from "@/shadcn/ui/button";
import { Card, CardContent } from "@/shadcn/ui/card";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/shadcn/ui/form";
import { Input } from "@/shadcn/ui/input";
import { Textarea } from "@/shadcn/ui/textarea";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm, type ControllerRenderProps } from "react-hook-form";
import { z } from "zod";
import { toast } from "sonner";
import { Eye, EyeOff, Copy, Check } from "lucide-react";
import { SchoolFormCardSkeleton } from "./loading";
import { authClient } from "@/src/auth-client";
import { useUser } from "@/contexts/user-context";
import { getBetterAuthHttpStatus, getBetterAuthErrorMessage, organisationToFormValues, buildMetadataPayload } from "./helpers";
import { handleAuthRedirect } from "@/utils/auth-redirect";


// Organisation schema
// Convert empty strings to undefined and validate email if provided
const emailWithTransform = z
  .union([z.string(), z.undefined()])  // allow undefined or string values
  .transform((v) => (v && typeof v === 'string' && v.trim() !== "" ? v.trim() : undefined))  // convert non-string values or empty strings to undefined
  .refine(   // custom validation rule
    (val) => {
      // If undefined or empty, it's valid (optional field)
      if (!val) return true;   // pass undefined through
      // Otherwise, validate it's a valid email
      return z.email().safeParse(val).success;
    },
    { message: "Invalid email address" }
  )
  .nullable().optional();
const organizationSchema = z.object({
  id: z.string(),   // id is autogenerated by the database on creation when an admin approves an onboarding request
  name: z.string().trim().min(1, { message: "School name is required" }),
  slug: z.string().optional().default("autogenerate"),   // registration ID (defaults to "autogenerate" if not provided)
  // logo: z.string().optional(),  // no logo for now
  metadata: z.object({
    address: z.string().trim().min(1, { message: "Address is required" }),
    motto: z.string().max(500, { message: "Motto must be less than 500 characters" }).nullable().optional(),
    telephone: z.string().max(20, { message: "Telephone number must be less than 20 characters" }).nullable().optional(),
    email: emailWithTransform,
  }).optional(),
});
export type OrganizationFormValues = z.input<typeof organizationSchema>;  // Before-parse shape

// School form component
export function SchoolForm() {
  // use router to handle redirects
  const router = useRouter();
  const pathname = usePathname();

  // Org admin gate — disable action buttons for 
  // - non-orgadmin users cannot manage the school
  // - users who have not verified their email 
  // - users who have not enabled 2FA cannot manage the school
  const { user } = useUser();
  const canManage = user?.role === "orgadmin" && user.twoFactorEnabled === true && user.emailVerified === true;

  // Get the active organisation as the school
  const { data: activeOrganisation, isPending: isActiveOrganisationPending, error: activeOrganisationError, refetch: refetchActiveOrganisation } = authClient.useActiveOrganization();
  // On error, fall back to null. Otherwise, use the fetched school.
  const school = activeOrganisation ?? null;
  // organisation slug === registration id
  const [registrationId, setRegistrationId] = useState<string | null>(null);
  // flag to show/hide the copied icon
  const [copied, setCopied] = useState(false);
  // flag to show/hide the registration id
  const [showRegistrationId, setShowRegistrationId] = useState(false);

  // Retry active organisation fetch
  function retryActiveOrganisationFetch() {
    void refetchActiveOrganisation?.();
  }

  // Redirect if there is an error getting the active organisation and if the status is 401 or 403 (on page load)
  useEffect(() => {
    if (!activeOrganisationError) return;  // if there is no error, return
    const status = getBetterAuthHttpStatus(activeOrganisationError);
    if (status === 401) {  // Unauthorised due to not being authenticated
      router.replace(`/sign-in?redirect=${pathname}`);
    } else if (status === 403) {  // Forbidden due to not having permission to access the page
      router.replace("/forbidden");
    }
  }, [activeOrganisationError, router, pathname]);

  // handle copy to clipboard
  async function handleCopy() {
    if (!registrationId) return;
    try {
      await navigator.clipboard.writeText(registrationId);
      // show the copied icon
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error("Could not copy registration ID. Please copy it manually.");
    }
  }

  // form validation with zodResolver and default values
  const schoolForm = useForm<OrganizationFormValues>({
    resolver: zodResolver(organizationSchema),
    defaultValues: {
      name: "",
      slug: "autogenerate",
      metadata: { address: "", motto: "", telephone: "", email: "" },
    },
  });

  // Sync form + registrationId once the active organisation resolves
  useEffect(() => {
    // If there is no active organisation, return
    if (!activeOrganisation) return;
    // When the active organisation resolves, reset the form with the active organisation data
    schoolForm.reset(organisationToFormValues(activeOrganisation));
    // Also set the registration id
    setRegistrationId(activeOrganisation.slug ?? null);
  }, [activeOrganisation, schoolForm]);

  // Handle form submission
  async function onSubmit(formData: OrganizationFormValues) {
    if (!canManage) return;  // return early if the user is not an org admin
    // Otherwise, build the metadata payload
    try {
      const metadata = buildMetadataPayload(formData.metadata);
      if (school) {
        // If the school exists, update it
        if (!school?.id) {
          toast.error("Failed to save school information", {
            description: "School id is missing. Please refresh and try again.",
          });
          return;
        }
        // Otherwise, update the existing school
        // construct the update payload
        const updatePayload = {
          data: {
            // name omitted — school name is not editable from this form
            // slug omitted — registration ID is not editable from this form
            // name: undefined,
            // slug: undefined,
            metadata: {
              // address: metadata.address, // Likewise address
              // address: undefined,
              motto: metadata.motto,
              telephone: metadata.telephone,
              email: metadata.email,
            },
          },
          organizationId: school.id,
        }
        const { error: updateError } = await authClient.organization.update(updatePayload);
        // If there is an update error, throw it and handle the error in the catch block
        if (updateError) throw updateError;
        // If no error, reset dirty state, refetch, and show success toast
        schoolForm.reset(formData);
        retryActiveOrganisationFetch();
        toast.success("School information saved successfully", {
          description: "Your school details have been saved",
        });
      }
    } catch (err: unknown) {
      if (!handleAuthRedirect(err, { router, pathname })) {
        toast.error("Failed to save school information", {
          description: getBetterAuthErrorMessage(err, "An error occurred while saving the school information"),
        });
      }
    }
  }

  // Discard changes — revert to last saved organisation snapshot (or empty defaults on create)
  function handleDiscard() {
    if (activeOrganisation) {
      schoolForm.reset(organisationToFormValues(activeOrganisation));
      return;
    }
    schoolForm.reset();
  }

  const isComponentLoading = isActiveOrganisationPending;

  return (
    <>
      {/* Page Header */}
      <SchoolAndTermMgt title="School Management" />

      {/* Shown if 2FA is not yet enabled */}
      <SecuritySetupModal />

      {/* Error banner — shown inline so the header and security modal remain visible */}
      {activeOrganisationError && (
        <ErrorBanner
          title="Could not load school information"
          message={getBetterAuthErrorMessage(
            activeOrganisationError,
            "Failed to load saved school information. Please try again.",
          )}
          onRetry={retryActiveOrganisationFetch}
        />
      )}

      {/* School Form Card — skeleton while active org resolves; hidden on fetch error */}
      {isComponentLoading ? (
        <SchoolFormCardSkeleton />
      ) : !activeOrganisationError && !activeOrganisation ? (
        <Card className="border shadow-md">
          <CardContent>
            <p>No school information found. Please contact your admin if you believe this is an error.</p>
          </CardContent>
        </Card>
      ) : !activeOrganisationError && (
        <Card className="border shadow-md">
          <CardContent>
            <Form {...schoolForm}>
              <form onSubmit={schoolForm.handleSubmit(onSubmit)} className="space-y-4">

                {/* School Information Section */}
                <section className="space-y-4">

                  {/* School Name */}
                  <FormField
                    control={schoolForm.control}
                    name="name"
                    render={({ field }: { field: ControllerRenderProps<OrganizationFormValues, "name"> }) => (
                      <FormItem>
                        <FormLabel className="text-sm md:text-base text-muted-foreground font-semibold">
                          School Name<span className="text-destructive text-base">*</span>
                        </FormLabel>
                        <FormControl>
                          <Input
                            disabled
                            type="text"
                            {...field}
                            readOnly={true}
                            placeholder="Enter school name"
                            className="h-10 md:h-12 text-sm md:text-base transition-colors hover:border-input focus:border-primary"
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  {/* School Address */}
                  <FormField
                    control={schoolForm.control}
                    name="metadata.address"
                    render={({ field }: { field: ControllerRenderProps<OrganizationFormValues, "metadata.address"> }) => (
                      <FormItem>
                        <FormLabel className="text-sm md:text-base text-muted-foreground font-semibold">Address</FormLabel>
                        <FormControl>
                          <Input
                            type="text"
                            {...field}
                            value={field.value ?? ""}
                            disabled
                            readOnly={true}
                            placeholder="Enter school address or location"
                            className="h-10 md:h-12 text-sm md:text-base transition-colors hover:border-input focus:border-primary"
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  {/* School Motto */}
                  <FormField
                    control={schoolForm.control}
                    name="metadata.motto"
                    render={({ field }: { field: ControllerRenderProps<OrganizationFormValues, "metadata.motto"> }) => (
                      <FormItem>
                        <FormLabel className="text-sm md:text-base text-muted-foreground font-semibold">Motto</FormLabel>
                        <FormControl>
                          <Textarea
                            {...field}
                            value={field.value ?? ""}
                            readOnly={!canManage}
                            placeholder="Enter your school motto if you want this to appear on the result sheet"
                            className="min-h-20 text-sm md:text-base transition-colors hover:border-input focus:border-primary"
                            rows={3}
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  {/* School Telephone and Email */}
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <FormField
                      control={schoolForm.control}
                      name="metadata.telephone"
                      render={({ field }: { field: ControllerRenderProps<OrganizationFormValues, "metadata.telephone"> }) => (
                        <FormItem>
                          <FormLabel className="text-sm md:text-base text-muted-foreground font-semibold">Telephone</FormLabel>
                          <FormControl>
                            <Input
                              {...field}
                              value={field.value ?? ""}
                              readOnly={!canManage}
                              type="tel"
                              placeholder="Enter school telephone number"
                              className="h-10 md:h-12 text-sm md:text-base transition-colors hover:border-input focus:border-primary"
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    {/* School Email */}
                    <FormField
                      control={schoolForm.control}
                      name="metadata.email"
                      render={({ field }: { field: ControllerRenderProps<OrganizationFormValues, "metadata.email"> }) => (
                        <FormItem>
                          <FormLabel className="text-sm md:text-base text-muted-foreground font-semibold">Email</FormLabel>
                          <FormControl>
                            <Input
                              {...field}
                              value={field.value ?? ""}
                              readOnly={!canManage}
                              type="email"
                              placeholder="Enter school email address"
                              className="h-10 md:h-12 text-sm md:text-base transition-colors hover:border-input focus:border-primary"
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  </div>
                </section>

                {/* School Registration ID — shown once a school exists */}
                {registrationId && (
                  <section className="space-y-2 pt-4 border-t border-border">
                    <div>
                      <p className="text-sm md:text-base text-muted-foreground font-semibold">
                        School Registration ID
                      </p>
                      <p className="text-xs text-muted-foreground mt-0.5">
                        Share this ID with teachers so they can register and join your school.
                      </p>
                    </div>
                    <div className="relative">
                      {/* Readonly value */}
                      <Input
                        readOnly
                        disabled
                        type="text"
                        value={showRegistrationId ? registrationId : "*****************"}
                        className="h-12 md:h-14 text-sm md:text-base pr-20 font-mono disabled:opacity-100 disabled:cursor-default [&::-ms-reveal]:hidden"
                      />
                      {/* Eye toggle */}
                      <Button
                        type="button"
                        variant="ghost"
                        size="icon"
                        onClick={() => setShowRegistrationId((v) => !v)}
                        title={showRegistrationId ? "Hide registration ID" : "Show registration ID"}
                        aria-label={showRegistrationId ? "Hide registration ID" : "Show registration ID"}
                        className="absolute right-10 top-1/2 -translate-y-1/2 h-8 w-8 text-muted-foreground hover:text-foreground"
                      >
                        {showRegistrationId ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                      </Button>
                      {/* Copy to clipboard */}
                      <Button
                        type="button"
                        variant="ghost"
                        size="icon"
                        onClick={handleCopy}
                        title="Copy registration ID"
                        aria-label="Copy registration ID"
                        className="absolute right-1 top-1/2 -translate-y-1/2 h-8 w-8 text-muted-foreground hover:text-foreground"
                      >
                        {copied ? <Check className="h-4 w-4 text-green-500" /> : <Copy className="h-4 w-4" />}
                      </Button>
                    </div>
                  </section>
                )}

                {/* Submit / Discard Buttons */}
                {canManage && (
                  <div className="pt-4 border-t border-border mt-4">
                    <div className="flex justify-center gap-3">
                      {/* Discard Changes Button */}
                      <Button
                        type="button"
                        variant="outline"
                        disabled={!schoolForm.formState.isDirty || schoolForm.formState.isSubmitting}
                        onClick={handleDiscard}
                        className="w-max h-10 md:h-12 text-sm md:text-base font-medium shadow-sm hover:shadow transition-shadow cursor-pointer"
                      >
                        Discard Changes
                      </Button>
                      {/* Save Changes Button */}
                      <LoadingButton
                        type="submit"
                        loading={schoolForm.formState.isSubmitting}
                        disabled={!schoolForm.formState.isDirty}
                        className="w-max h-10 md:h-12 text-sm md:text-base font-medium shadow-sm hover:shadow transition-shadow cursor-pointer"
                      >
                        Save Changes
                      </LoadingButton>
                    </div>
                  </div>
                )}

              </form>
            </Form>
          </CardContent>
        </Card>
      )}
    </>
  );
}